# why do we use numpy


NumPy is a popular library for numerical computing in Python. There are several reasons why it's widely used:

Speed: NumPy is faster than the standard Python list data structure because it uses a fixed-sized contiguous block of memory to store its elements. This makes NumPy operations faster than those performed on lists.

Convenience: NumPy provides a large number of convenient functions for performing operations on arrays, including mathematical functions, linear algebra operations, and statistical functions.

Integration with other libraries: NumPy arrays can be easily integrated with other libraries in the scientific Python ecosystem, such as Matplotlib, Pandas, and SciPy, making it a versatile tool for data analysis and scientific computing.

Support for multidimensional arrays: NumPy supports the creation and manipulation of multidimensional arrays, which are essential for many scientific and engineering applications.

Overall, NumPy provides a fast, convenient, and powerful environment for numerical computing in Python, making it an essential tool for data scientists, machine learning practitioners, and researchers.







# why numpy arrays are faster than python lists

NumPy arrays are faster than lists in Python for several reasons:

Vectorized Operations: NumPy arrays support vectorized operations, which are computationally more efficient than traditional loops in Python. This is because NumPy operations are executed in a highly optimized C loop, while operations on Python lists are executed in a dynamic, interpreted environment.

Memory layout: NumPy arrays are stored in a contiguous block of memory, while lists are stored as a linked list of elements, which can be scattered across different memory locations. This contiguous memory layout makes NumPy arrays more cache-friendly and enables faster indexing and slicing operations.

Type consistency: In NumPy, all elements of an array must be of the same type, while in Python lists, elements can be of different types. Having a homogeneous data type enables NumPy to use more efficient algorithms for computation and reduces the overhead of type checking.

Broadcasting: NumPy supports broadcasting, which allows for efficient operations between arrays of different shapes. Broadcasting enables you to perform operations between arrays without having to write explicit for loops, which can be computationally expensive in Python.

In summary, NumPy arrays are faster than lists because they are more optimized for numerical computation, have a more efficient memory layout, enforce type consistency, and support broadcasting.



# Important Points own 

# numpy

In [1]:
import numpy
a=numpy.array(1)#creating a ndarray using the numpy.array() method or function
print(type(a))
#b=numpy.array(1,2) #shows error u need to use any array type object inside the array method to pass more than one value
c=numpy.array([1,2,3])
#or
d=numpy.array((0,9,8))
print(c)
print(d)
print(a)
#accessing particular elements of ndarray
print(c[0])#using [] bcz we know syntax is using [] in python to access list

import numpy as np
a=np.array([1,2,3])
print(a.ndim)


<class 'numpy.ndarray'>
[1 2 3]
[0 9 8]
1
1
1




# higher dimension  ndim(no of dimensions)

In [40]:
import numpy as kk
a=kk.array([1,2,3,4],ndmin=5)#NOTE: ndmin HERE NOT ndim
print(a)
"""In this array the innermost dimension (5th dim) has 4 elements, the 4th dim has 1 element that is the vector, the 3rd dim has 1 element that is the matrix with the vector, the 2nd dim has 1 element that is 3D array and 1st dim has 1 element that is a 4D array."""

[[[[[1 2 3 4]]]]]


'In this array the innermost dimension (5th dim) has 4 elements, the 4th dim has 1 element that is the vector, the 3rd dim has 1 element that is the matrix with the vector, the 2nd dim has 1 element that is 3D array and 1st dim has 1 element that is a 4D array.'