# ndim

ndim is a property of a NumPy array, not a function. It is used to determine the number of dimensions in an array.

In NumPy, an array can be thought of as a grid of values, where each value is called an element. The number of dimensions of an array is the number of indices required to access a single element of the array. For example, a 1-dimensional array would be a simple vector, where each element can be accessed by a single index, whereas a 2-dimensional array would be a matrix, where each element requires two indices to be accessed.

The ndim property returns the number of dimensions in a NumPy array. You can access the ndim property by simply referencing it as an attribute of the NumPy array object:

import numpy as np

a = np.array([1, 2, 3, 4])
print(a.ndim)  # Output: 1

b = np.array([[1, 2, 3], [4, 5, 6]])
print(b.ndim)  # Output: 2


In the example above, the ndim property returns 1 for the 1-dimensional array a and 2 for the 2-dimensional array b.

# 0d

In [9]:
import numpy as np
a=np.array(0)
print(a.ndim)

0


# 1d

In [10]:
a=np.array([1,2,3])
#a=np.array([1,2,3],[4,5,6])this doesnt work bcz first rule is if u want to give more than one value to a ndarray u must use any array like obj such as list,tuple
print(a.ndim)

1


# 2d

In [26]:
#ex1
a=np.array([[1,2,3],[4,5,6]])#this line creates a matrix of 2X3 matrix 2 rows 3 cols
print(a.ndim)
print(a.shape)
#ex2
b=np.array([[1,2],[4,5],[6,7]])#this line creates a matrix of 3X2 matrix 3 rows 2 cols
print(b.ndim)
print(b.shape)
#ex3
c=np.array([[1,2]])#this line creates a matrix of 1X2 matrix 1 rows 2 cols
print(c.ndim) 
print(c.shape)
#ex4
d=np.array([[1,2],[7,8],[9]])
#here the 3rd 1d array which is [9] is not as same shape ([1,2],[7,8])


2
(2, 3)
2
(3, 2)
2
(1, 2)


/var/folders/j2/7vzyj65535sdpxn_vd38sncm0000gn/T/ipykernel_2860/2131387858.py:14: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  d=np.array([[1,2],[7,8],[9]])


# 3d(assume 3d array as cube of 2d matrices as layers)

In [31]:
#imp point
#1)list of 2d arrays is said to be a 3 dimensional array even the list with one 2d array is also a 3d array with shape (1,(shape of 2d array))

#exp1
a=np.array([[[1,2,3],[4,5,6]],[[8,9,0],[3,5,6]]])#here a is 3d array with two 2d arrays 
print(a.ndim)
print(a.shape)#returns(noofmatrices,no.of.rows,no.of.columns)

#exp2
b=np.array([[[1,2,3]]])
print(b.ndim)
print(b.shape)

#exp3 
c=np.array([[[1,2,3],[4,5,6]],[[9,99,999]]])
#the above one shows error bcz see in the list of 2d arrays see shape of first 2d arrya which is (2X3) matrix but the second 2d array is of (1X3) which is not same as the first 2d array so it coudnt be placed as a layer of cube

3
(2, 2, 3)
3
(1, 1, 3)


/var/folders/j2/7vzyj65535sdpxn_vd38sncm0000gn/T/ipykernel_2860/1345998098.py:15: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  c=np.array([[[1,2,3],[4,5,6]],[[9,99,999]]])


# HIGHER DIMENSION(HOW TO CREATE AN OF DIMENSION MORE THAN 3 WHICH IS DIFFICULT 

In [43]:
a=np.array([[1,2,3]],ndmin=4)#NOTE: ndmin(minimum no.of dimensions) HERE NOT ndim
print(a)
print(a.ndim)
#exp for above code:her a is of 2dimension by usage of ndimn the dimension of array are moved to 4

         #what if we try to decrease the dimensions of a array
b=np.array([[1,2,3],[4,5,6]],ndmin=1)
print(b)
print(b.ndim)

##exp for above code: see above the array b is of dimension 2 but we mentioned 1 in ndmin i.e., we tried to decrease the dimension but if we look at the output it doesn execute which means we cant decrease the dimensions of an array which in fact is also impossible with respect to mathematical nature

[[[[1 2 3]]]]
4
[[1 2 3]
 [4 5 6]]
2


#                        # array indexing


#accesing ele in 1d array

In [48]:
a=np.array([1,2,3])
print(a[0])#access ele at index one of 1d array
print(a[2])

1
3


#accessing ele in 2d array

In [52]:
b=np.array([[4,5,6],[7,8,9]])
print(b[1][2])#1)in first list goes to list of index 1 then goes to ele of index 2 in that so prints 9
print(b[0][1])

9
5


#accessing ele in 3d array

In [55]:
c=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[77,88,99]]])
print(c[0][1][2])
"""
1)goes to 1st list in the list bcz index mentioned is0(which means goes to first 2d array(i.e.first matrix))
2)then goes to second list in the 2d array(matrix) as index in 1
3)and finally meets the ele 6 which is the ele in the 1d arry of 2d array of 3d array with index 2
3)so prints 6

"""
print(c[1][1][2])

6
99


# SLICING OF ARRAYS

SLICING 1D ARRAYS

In [63]:
"""
SYNTAX:
    arrayname[startindex:stopindex]
            (or)
    arrayname[startindex:stopindex:step]
"""
a=np.array([1,2,3,4])
print(a[1:3])

                        #negative slicing on 1d arrays
print(a[-3:-1])#here it is not printing the element at index one so below is how to include the ele at index 1 also
print(a[-3:])

                        #slicing using step
print(a[0:4:2])#NOTE:STEP IS LIKE SEE IN ARRAY A IF STEP IS 2 THEN AS START INDEX IS 0 SO IT WILL BE PRINTED THEN THE NEXT STEP WHICH IS FIRSTSTEP GOES TO ELEMENT 2 THIS WILL NOT BE PRINTED BCZ STEP IS 2 BUT WE ARE AT STEP 1 SO 1 MORE STEP THEN GOES TO ELE 3 AS WE ARE STEP 2 IT WILL BE PRINTED NEXT AND THEN TAKE 2 STEP THEN GOES TO INDEX WHERE THERE IS NO ELE SO AT LAST PRINTS TWO ELEMENTS 1,3

[2 3]
[2 3]
[2 3 4]
[1 3]


SLICING 2D ARRAYS

In [2]:
import numpy as np
a=np.array([[1,2,3,4,5,6],[7,8,9,10,11,12],[13,14,15,16,17,18]])
            #two ways to slice two dimensional arrays but not in all cases
#EXP1
print(a[0][1:4])
print(a[0,1:4])

#exp2
print("exp2")
print(a[0:2][1:4])#see this one isnt working
print(a[0:2,1:4])

#exp3
print(a[0:2][1])#see this isnt working
print(a[0:2,1])


[2 3 4]
[2 3 4]
exp2
[[ 7  8  9 10 11 12]]
[[ 2  3  4]
 [ 8  9 10]]
[ 7  8  9 10 11 12]
[2 8]
